version: 1.0.{build}
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\ConsoleAppDapper.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  disable_publish_on_pr: true
  disable_publish_octopus: true
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  publish_aspnet_core: true
  publish_core_console: true
  verbosity: minimal